# @package _group_

nq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-train

nq_train_hn1:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-adv-hn-train

nq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.nq-dev

trivia_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-train

trivia_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.trivia-dev

squad1_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-train

squad1_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.squad1-dev

webq_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-train

webq_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.webq-dev

curatedtrec_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-train

curatedtrec_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.curatedtrec-dev

defeasible_snli_strengthener_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/intern2/seungone/ConEV/data/dpr_style/defeasible_strengthener_snli_train.json"

defeasible_snli_strengthener_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/intern2/seungone/ConEV/data/dpr_style/defeasible_strengthener_snli_val.json"

defeasible_snli_weakener_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/intern2/seungone/ConEV/data/dpr_style/defeasible_weakener_snli_train.json"

defeasible_snli_weakener_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/intern2/seungone/ConEV/data/dpr_style/defeasible_weakener_snli_val.json"