# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test
  #query_special_suffix: '?'

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test

curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test

defeasible_snli_strengthener_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/intern2/seungone/ConEV/data/dpr_style/defeasible_strengthener_snli_train.json"

defeasible_snli_strengthener_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/intern2/seungone/ConEV/data/dpr_style/defeasible_strengthener_snli_val.json"

defeasible_snli_weakener_train:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/intern2/seungone/ConEV/data/dpr_style/defeasible_weakener_snli_train.json"

defeasible_snli_weakener_dev:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: "/home/intern2/seungone/ConEV/data/dpr_style/defeasible_weakener_snli_val.json"